(function () {
  const STR = {
    es: {
      doc_title: "Audiora - Reproductor Musical",
      nav_home: "Inicio",
      nav_explore: "Explorar",
      create_playlist: "Crear playlist",
      library_yours: "Tu Biblioteca",
      likes: "Tus Me Gusta",
      recent: "Recientes",
      search_ph: "¿Qué quieres reproducir?",
      browse_aria: "Explorar categorías",
      top_home_aria: "Inicio",
      user_btn: "Usuario",
      tab_all: "Todo",
      tab_music: "Música",
      tab_artists: "Artistas",
      greeting: "Buenas tardes",
      title_music: "Música",
      title_artists: "Artistas",
      explore_all: "Explorar todo",
      section_artists: "Artistas",
      library_header: "Tu Biblioteca",
      lib_playlists: "Playlists",
      lib_artists: "Artistas",
      no_results: "No se encontraron resultados",
      now_playing: "EN REPRODUCCIÓN",
      cover_alt: "Portada",
      panel_pick: "Selecciona una canción",
      panel_artist: "Artista",
      queue_title: "Cola de reproducción",
      queue_empty: "No hay canciones en cola",
      footer_idle: "Sin reproducción",
      search_results: 'Resultados para "{{term}}"',
      song_count: "{{n}} canciones",
      word_artist: "Artista",
      lang_label: "Idioma",
      playlist_dev: "Funcionalidad de crear playlist en desarrollo",
    },
    en: {
      doc_title: "Audiora - Music Player",
      nav_home: "Home",
      nav_explore: "Explore",
      create_playlist: "Create playlist",
      library_yours: "Your Library",
      likes: "Liked Songs",
      recent: "Recently played",
      search_ph: "What do you want to play?",
      browse_aria: "Browse categories",
      top_home_aria: "Home",
      user_btn: "User",
      tab_all: "All",
      tab_music: "Music",
      tab_artists: "Artists",
      greeting: "Good afternoon",
      title_music: "Music",
      title_artists: "Artists",
      explore_all: "Browse all",
      section_artists: "Artists",
      library_header: "Your Library",
      lib_playlists: "Playlists",
      lib_artists: "Artists",
      no_results: "No results found",
      now_playing: "NOW PLAYING",
      cover_alt: "Cover art",
      panel_pick: "Pick a song",
      panel_artist: "Artist",
      queue_title: "Queue",
      queue_empty: "Nothing in the queue",
      footer_idle: "Not playing",
      search_results: 'Results for "{{term}}"',
      song_count: "{{n}} songs",
      word_artist: "Artist",
      lang_label: "Language",
      playlist_dev: "Create playlist is under development",
    },
    pt: {
      doc_title: "Audiora - Reprodutor musical",
      nav_home: "Início",
      nav_explore: "Explorar",
      create_playlist: "Criar playlist",
      library_yours: "Sua biblioteca",
      likes: "Músicas curtidas",
      recent: "Tocados recentemente",
      search_ph: "O que você quer ouvir?",
      browse_aria: "Explorar categorias",
      top_home_aria: "Início",
      user_btn: "Usuário",
      tab_all: "Tudo",
      tab_music: "Música",
      tab_artists: "Artistas",
      greeting: "Boa tarde",
      title_music: "Música",
      title_artists: "Artistas",
      explore_all: "Explorar tudo",
      section_artists: "Artistas",
      library_header: "Sua biblioteca",
      lib_playlists: "Playlists",
      lib_artists: "Artistas",
      no_results: "Nenhum resultado encontrado",
      now_playing: "TOCANDO AGORA",
      cover_alt: "Capa",
      panel_pick: "Escolha uma música",
      panel_artist: "Artista",
      queue_title: "Fila de reprodução",
      queue_empty: "Nada na fila",
      footer_idle: "Sem reprodução",
      search_results: 'Resultados para "{{term}}"',
      song_count: "{{n}} músicas",
      word_artist: "Artista",
      lang_label: "Idioma",
      playlist_dev: "Criar playlist em desenvolvimento",
    },
    de: {
      doc_title: "Audiora – Musikplayer",
      nav_home: "Start",
      nav_explore: "Entdecken",
      create_playlist: "Playlist erstellen",
      library_yours: "Deine Bibliothek",
      likes: "Lieblingssongs",
      recent: "Zuletzt gespielt",
      search_ph: "Was möchtest du hören?",
      browse_aria: "Kategorien durchsuchen",
      top_home_aria: "Start",
      user_btn: "Nutzer",
      tab_all: "Alle",
      tab_music: "Musik",
      tab_artists: "Künstler",
      greeting: "Guten Tag",
      title_music: "Musik",
      title_artists: "Künstler",
      explore_all: "Alles durchsuchen",
      section_artists: "Künstler",
      library_header: "Deine Bibliothek",
      lib_playlists: "Playlists",
      lib_artists: "Künstler",
      no_results: "Keine Ergebnisse",
      now_playing: "WIRD WIEDERGEGEBEN",
      cover_alt: "Cover",
      panel_pick: "Song auswählen",
      panel_artist: "Künstler",
      queue_title: "Warteschlange",
      queue_empty: "Keine Songs in der Warteschlange",
      footer_idle: "Keine Wiedergabe",
      search_results: 'Ergebnisse für „{{term}}“',
      song_count: "{{n}} Titel",
      word_artist: "Künstler",
      lang_label: "Sprache",
      playlist_dev: "Playlist erstellen ist in Entwicklung",
    },
    it: {
      doc_title: "Audiora - Lettore musicale",
      nav_home: "Home",
      nav_explore: "Esplora",
      create_playlist: "Crea playlist",
      library_yours: "La tua libreria",
      likes: "Brani che ti piacciono",
      recent: "Riprodotti di recente",
      search_ph: "Cosa vuoi ascoltare?",
      browse_aria: "Sfoglia le categorie",
      top_home_aria: "Home",
      user_btn: "Utente",
      tab_all: "Tutto",
      tab_music: "Musica",
      tab_artists: "Artisti",
      greeting: "Buon pomeriggio",
      title_music: "Musica",
      title_artists: "Artisti",
      explore_all: "Sfoglia tutto",
      section_artists: "Artisti",
      library_header: "La tua libreria",
      lib_playlists: "Playlist",
      lib_artists: "Artisti",
      no_results: "Nessun risultato",
      now_playing: "IN RIPRODUZIONE",
      cover_alt: "Copertina",
      panel_pick: "Scegli un brano",
      panel_artist: "Artista",
      queue_title: "Coda di riproduzione",
      queue_empty: "Nessun brano in coda",
      footer_idle: "Nessuna riproduzione",
      search_results: 'Risultati per "{{term}}"',
      song_count: "{{n}} brani",
      word_artist: "Artista",
      lang_label: "Lingua",
      playlist_dev: "Creazione playlist in sviluppo",
    },
    ru: {
      doc_title: "Audiora — музыкальный плеер",
      nav_home: "Главная",
      nav_explore: "Обзор",
      create_playlist: "Создать плейлист",
      library_yours: "Моя медиатека",
      likes: "Любимые треки",
      recent: "Недавно прослушано",
      search_ph: "Что вы хотите послушать?",
      browse_aria: "Обзор категорий",
      top_home_aria: "Главная",
      user_btn: "Пользователь",
      tab_all: "Всё",
      tab_music: "Музыка",
      tab_artists: "Исполнители",
      greeting: "Добрый день",
      title_music: "Музыка",
      title_artists: "Исполнители",
      explore_all: "Обзор всего",
      section_artists: "Исполнители",
      library_header: "Моя медиатека",
      lib_playlists: "Плейлисты",
      lib_artists: "Исполнители",
      no_results: "Ничего не найдено",
      now_playing: "СЕЙЧАС ИГРАЕТ",
      cover_alt: "Обложка",
      panel_pick: "Выберите трек",
      panel_artist: "Исполнитель",
      queue_title: "Очередь",
      queue_empty: "В очереди нет треков",
      footer_idle: "Нет воспроизведения",
      search_results: 'Результаты по запросу «{{term}}»',
      song_count: "{{n}} треков",
      word_artist: "Исполнитель",
      lang_label: "Язык",
      playlist_dev: "Создание плейлиста в разработке",
    },
    ja: {
      doc_title: "Audiora - ミュージックプレーヤー",
      nav_home: "ホーム",
      nav_explore: "さがす",
      create_playlist: "プレイリストを作成",
      library_yours: "あなたのライブラリ",
      likes: "お気に入りの曲",
      recent: "最近再生した項目",
      search_ph: "何を再生しますか？",
      browse_aria: "カテゴリを見る",
      top_home_aria: "ホーム",
      user_btn: "ユーザー",
      tab_all: "すべて",
      tab_music: "ミュージック",
      tab_artists: "アーティスト",
      greeting: "こんにちは",
      title_music: "ミュージック",
      title_artists: "アーティスト",
      explore_all: "すべてを見る",
      section_artists: "アーティスト",
      library_header: "あなたのライブラリ",
      lib_playlists: "プレイリスト",
      lib_artists: "アーティスト",
      no_results: "結果が見つかりません",
      now_playing: "再生中",
      cover_alt: "カバー画像",
      panel_pick: "曲を選択",
      panel_artist: "アーティスト",
      queue_title: "再生キュー",
      queue_empty: "キューに曲がありません",
      footer_idle: "再生していません",
      search_results: '「{{term}}」の検索結果',
      song_count: "{{n}} 曲",
      word_artist: "アーティスト",
      lang_label: "言語",
      playlist_dev: "プレイリスト作成は開発中です",
    },
    ko: {
      doc_title: "Audiora - 뮤직 플레이어",
      nav_home: "홈",
      nav_explore: "둘러보기",
      create_playlist: "플레이리스트 만들기",
      library_yours: "내 라이브러리",
      likes: "좋아요 표시한 곡",
      recent: "최근 재생",
      search_ph: "무엇을 재생할까요?",
      browse_aria: "카테고리 둘러보기",
      top_home_aria: "홈",
      user_btn: "사용자",
      tab_all: "전체",
      tab_music: "음악",
      tab_artists: "아티스트",
      greeting: "안녕하세요",
      title_music: "음악",
      title_artists: "아티스트",
      explore_all: "모두 둘러보기",
      section_artists: "아티스트",
      library_header: "내 라이브러리",
      lib_playlists: "플레이리스트",
      lib_artists: "아티스트",
      no_results: "결과 없음",
      now_playing: "재생 중",
      cover_alt: "커버 아트",
      panel_pick: "곡을 선택하세요",
      panel_artist: "아티스트",
      queue_title: "재생 대기열",
      queue_empty: "대기열에 곡이 없습니다",
      footer_idle: "재생 중 아님",
      search_results: '"{{term}}" 검색 결과',
      song_count: "{{n}}곡",
      word_artist: "아티스트",
      lang_label: "언어",
      playlist_dev: "플레이리스트 만들기 기능 개발 중",
    },
    zh: {
      doc_title: "Audiora - 音乐播放器",
      nav_home: "首页",
      nav_explore: "浏览",
      create_playlist: "创建播放列表",
      library_yours: "你的音乐库",
      likes: "喜欢的歌曲",
      recent: "最近播放",
      search_ph: "想播放什么？",
      browse_aria: "浏览分类",
      top_home_aria: "首页",
      user_btn: "用户",
      tab_all: "全部",
      tab_music: "音乐",
      tab_artists: "艺人",
      greeting: "下午好",
      title_music: "音乐",
      title_artists: "艺人",
      explore_all: "浏览全部",
      section_artists: "艺人",
      library_header: "你的音乐库",
      lib_playlists: "播放列表",
      lib_artists: "艺人",
      no_results: "未找到结果",
      now_playing: "正在播放",
      cover_alt: "封面",
      panel_pick: "选择歌曲",
      panel_artist: "艺人",
      queue_title: "播放队列",
      queue_empty: "队列为空",
      footer_idle: "未在播放",
      search_results: "“{{term}}”的搜索结果",
      song_count: "{{n}} 首歌曲",
      word_artist: "艺人",
      lang_label: "语言",
      playlist_dev: "创建播放列表功能开发中",
    },
  };

  const LANGS = [
    { code: "es", label: "Español", badge: "ES" },
    { code: "en", label: "English", badge: "EN" },
    { code: "pt", label: "Português", badge: "PT" },
    { code: "de", label: "Deutsch", badge: "DE" },
    { code: "it", label: "Italiano", badge: "IT" },
    { code: "ru", label: "Русский", badge: "RU" },
    { code: "ja", label: "日本語", badge: "JA" },
    { code: "ko", label: "한국어", badge: "KO" },
    { code: "zh", label: "中文", badge: "ZH" },
  ];

  const HTML_LANG_MAP = {
    zh: "zh-CN",
  };

  let lang = localStorage.getItem("app-lang") || "es";
  if (!STR[lang]) lang = "es";

  function interpolate(str, vars) {
    if (!vars || typeof str !== "string") return str;
    return str.replace(/\{\{(\w+)\}\}/g, (_, k) =>
      vars[k] !== undefined && vars[k] !== null ? String(vars[k]) : "",
    );
  }

  function t(key, vars) {
    const pack = STR[lang] || STR.es;
    const raw = pack[key] !== undefined ? pack[key] : STR.es[key] !== undefined ? STR.es[key] : key;
    return interpolate(raw, vars);
  }

  function applyToDocument() {
    document.documentElement.lang = HTML_LANG_MAP[lang] || lang;
    document.querySelectorAll("[data-i18n]").forEach((el) => {
      const key = el.getAttribute("data-i18n");
      if (!key) return;
      const val = t(key);
      if (el.tagName === "INPUT" || el.tagName === "TEXTAREA") {
        el.placeholder = val;
      } else {
        el.textContent = val;
      }
    });
    document.querySelectorAll("[data-i18n-aria]").forEach((el) => {
      const key = el.getAttribute("data-i18n-aria");
      if (key) el.setAttribute("aria-label", t(key));
    });
    document.querySelectorAll("[data-i18n-alt]").forEach((el) => {
      const key = el.getAttribute("data-i18n-alt");
      if (key) el.setAttribute("alt", t(key));
    });
    document.title = t("doc_title");
    const label = document.getElementById("current-lang-label");
    if (label) {
      const meta = LANGS.find((l) => l.code === lang);
      label.textContent = meta ? meta.label : lang;
    }
    document.querySelectorAll(".language-option").forEach((li) => {
      const c = li.getAttribute("data-lang");
      li.classList.toggle("is-selected", c === lang);
      li.setAttribute("aria-selected", c === lang ? "true" : "false");
    });
  }

  function setLanguage(code) {
    if (!STR[code]) code = "es";
    lang = code;
    localStorage.setItem("app-lang", lang);
    applyToDocument();
    window.dispatchEvent(new CustomEvent("app:languagechange", { detail: { lang } }));
  }

  function getLanguage() {
    return lang;
  }

  window.AppI18n = {
    t,
    setLanguage,
    getLanguage,
    applyToDocument,
    LANGS,
  };
})();
